### ISSUE TITLE
Issue with 3 inputs (cluster io stats, node io stats, node stats)

### ISSUE THREAD

**Issue by UncleNasty1** [rubrikinc/rubrik-addon-for-splunk#29]
I'm having an issue with 3 specific inputs that are not collecting log data from Rubrik. 

I will list the inputs down below:
1. Rubrik Cluster IO Stats
2. Rubrik Node IO Stats
3. Rubrik Node Stats

I put the logging info in the Rubrik Add-on to DEBUG and I'm getting the following errors. I'm not sure what the IndexError: List index out of range means. Do I have to update python for it to work? Has anyone else seen issues with this?

2021-11-30 14:30:10,763 INFO pid=32022 tid=MainThread file=setup_util.py:log_info:117 | Log level is not set, use default INFO
2021-11-30 14:30:10,764 INFO pid=32022 tid=MainThread file=base_modinput.py:log_info:295 | Running query for pan-adm-rub.pan.cmcc
2021-11-30 14:30:11,494 ERROR pid=32022 tid=MainThread file=base_modinput.py:log_error:309 | Get error when collecting events.
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/TA-rubrik-splunk-add-on/bin/ta_rubrik_splunk_add_on/aob_py3/modinput_wrapper/base_modinput.py", line 128, in stream_events
    self.collect_events(ew)
  File "/opt/splunk/etc/apps/TA-rubrik-splunk-add-on/bin/rubrik_node_io_stats.py", line 76, in collect_events
    input_module.collect_events(self, ew)
  File "/opt/splunk/etc/apps/TA-rubrik-splunk-add-on/bin/input_module_rubrik_node_io_stats.py", line 93, in collect_events
    output['_time'] = response['iops']['readsPerSecond'][-1]['time']^C
IndexError: list index out of range

**Comment by UncleNasty1** [comment]
We are on the latest version Rubrik and Splunk
